# Generated by Django 5.0.7 on 2024-07-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EMP_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=6)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("photo", models.ImageField(upload_to="Profile-Image")),
                ("department", models.CharField(max_length=200)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("join_date", models.DateField()),
                ("position", models.CharField(max_length=200)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=6, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="Manager")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("manager_id", models.CharField(max_length=6, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("password2", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manager_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager", models.CharField(max_length=6)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EMP_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_sale", models.IntegerField()),
                ("product_purchase", models.IntegerField()),
                ("total_sales", models.IntegerField()),
                ("total_purchase", models.IntegerField()),
                ("profit", models.IntegerField()),
                ("emp_salary", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Create_acc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=50)),
                ("password2", models.CharField(max_length=50)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.employee"
                    ),
                ),
            ],
        ),
    ]
